spring:
  jpa:
    hibernate:
      ddl-auto: create
  data:
    rest:
      detection-strategy: all

server:
  port: 9080
  error:
    whitelabel:
      enabled: false
management:
  security:
    enabled: false
